[project]
name = "polare-docs"
version = "0.1.0"
description = "Documentação do sistema Polare"
authors = [
    {name = "Igor Carvalho",email = "igbrch@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "invoke (>=2.2.1,<3.0.0)",
    "pygments (>=2.19.2,<3.0.0)",
    "rstcheck (>=6.2.5,<7.0.0)",
    "sphinx-autobuild (>=2025.8.25,<2026.0.0)",
    "sphinx-hoverxref (>=1.4.2,<2.0.0)",
    "sphinx-rtd-theme (>=3.0.2,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
